# Generated by Django 5.1.4 on 2025-01-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_compte_utilisateurprofil_delete_profilutilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='etat',
            field=models.CharField(choices=[('admin', 'Admin'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=20),
        ),
        migrations.AddField(
            model_name='compte',
            name='taille',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurprofil',
            name='etat_utilisateur',
            field=models.CharField(choices=[('admin', 'Admin'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateurprofil',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='utilisateurprofil',
            name='role',
            field=models.CharField(choices=[('pharmacien', 'Pharmacien'), ('caissier', 'Caissier'), ('gestionnaire', 'Gestionnaire'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
