# Generated by Django 5.1.4 on 2025-02-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_compte_etat_compte_taille_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='abonnement_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='dernier_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
