# Generated by Django 5.1.4 on 2024-12-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='facture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='Produits.facture_client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture_client',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
