# Generated by Django 5.1.4 on 2024-12-15 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0003_rename_total_amount_vente_montant_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture_client',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='Produits.customer'),
        ),
    ]
