# Generated by Django 5.1.4 on 2024-12-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0004_alter_facture_client_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.customer'),
        ),
    ]
