# Generated by Django 5.1.4 on 2024-12-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0005_alter_vente_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
