# Generated by Django 5.1.4 on 2025-01-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0006_alter_vente_montant_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture_client',
            name='remise_globale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
