# Generated by Django 5.1.4 on 2025-01-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0008_factureachat_alter_facture_client_remise_globale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='facture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Produits.factureachat'),
            preserve_default=False,
        ),
    ]
