# Generated by Django 5.1.4 on 2025-01-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0010_achat_date_expiration_alter_achat_facture_stocklot'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureachat',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
