# Generated by Django 5.1.4 on 2025-01-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0013_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='utilisateur',
        ),
    ]
