# Generated by Django 5.1.4 on 2025-01-09 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0015_produitcommande_devis_bondecommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureachat',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='Produits.achat'),
            preserve_default=False,
        ),
    ]
