# Generated by Django 5.1.4 on 2025-01-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0016_factureachat_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=60)),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
            ],
        ),
    ]
