# Generated by Django 5.1.4 on 2025-01-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0017_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factureachat',
            name='supplier',
        ),
    ]
