# Generated by Django 5.1.4 on 2025-01-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0018_remove_factureachat_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='adress',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='factureachat',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur', to='Produits.fournisseur'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
