# Generated by Django 5.1.4 on 2025-01-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0021_bondecommande_prix_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondecommande',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Produits.produits'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='commandefact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='Produits.fournisseur')),
            ],
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='commande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='Produits.commandefact'),
            preserve_default=False,
        ),
    ]
