# Generated by Django 5.1.4 on 2025-01-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0022_bondecommande_produit_commandefact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondecommande',
            name='produits',
        ),
    ]
