# Generated by Django 5.1.4 on 2025-01-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0023_remove_bondecommande_produits'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondecommande',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
