# Generated by Django 5.1.4 on 2025-01-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0024_bondecommande_quantite_alter_bondecommande_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bondecommande',
            unique_together={('commande', 'produit')},
        ),
    ]
