# Generated by Django 5.1.4 on 2025-01-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0026_alter_bondecommande_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bondecommande',
            old_name='commande',
            new_name='commandefac',
        ),
    ]
