# Generated by Django 5.1.4 on 2025-01-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0029_remove_devis_date_devis_remove_devis_produits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devisfact',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
