# Generated by Django 5.1.4 on 2025-01-13 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0030_devisfact_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='devisfac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviss', to='Produits.devisfact'),
        ),
    ]
