# Generated by Django 5.1.4 on 2025-01-13 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0031_alter_devis_devisfac'),
    ]

    operations = [
        migrations.AddField(
            model_name='devisfact',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Produits.customer'),
            preserve_default=False,
        ),
    ]
