# Generated by Django 5.1.4 on 2025-01-13 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0032_devisfact_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devisfact',
            name='produit',
        ),
        migrations.AddField(
            model_name='devis',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Produits.produits'),
            preserve_default=False,
        ),
    ]
