# Generated by Django 5.1.4 on 2025-01-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0037_alter_devis_total_alter_devisfact_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='devisfact',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
