# Generated by Django 5.1.4 on 2025-01-16 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0038_alter_devis_total_alter_devisfact_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
