# Generated by Django 5.1.4 on 2025-01-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0039_devis_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='date_derniere_notification',
            field=models.DateField(blank=True, null=True),
        ),
    ]
