# Generated by Django 5.1.4 on 2025-01-26 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0040_stocklot_date_derniere_notification'),
        ('utilisateurs', '0002_compte_utilisateurprofil_delete_profilutilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='name',
        ),
        migrations.AddField(
            model_name='achat',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='achat', to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boncommande', to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commandefact',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commandefac', to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devisfact',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devisfac', to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture_client',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fac', to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factureachat',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facachat', to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur', to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiqueprix',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametre',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produits',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produitsvente',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produitsvente', to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklot',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stocklot', to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockminimum',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.compte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='compte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vente', to='utilisateurs.compte'),
            preserve_default=False,
        ),
    ]
