# Generated by Django 5.1.4 on 2025-01-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0044_alter_parametre_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('expirant', 'Expiration imminente'), ('stock_minimum', 'Stock minimum atteint'), ('remise', 'Remise appliquée'), ('motivation', 'motivation'), ('proche_expiration', 'perime'), ('autre', 'Autre')], max_length=20),
        ),
    ]
