# Generated by Django 5.1.4 on 2025-01-30 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0045_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='produits',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
