# Generated by Django 5.1.4 on 2025-01-30 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0046_produits_slug_produits_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
