# Generated by Django 5.1.4 on 2025-01-30 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0047_alter_produits_slug_alter_produits_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
