# Generated by Django 5.1.4 on 2025-01-30 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0048_stocklot_slug_stocklot_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklot',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
