# Generated by Django 5.1.4 on 2025-01-30 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0049_alter_stocklot_slug_alter_stocklot_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture_client',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
