# Generated by Django 5.1.4 on 2025-01-30 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0050_facture_client_uuid_vente_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture_client',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
