# Generated by Django 5.1.4 on 2025-02-03 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0052_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='date_expiration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
